spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/runescape
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.h2.console.enabled=true
security.basic.enabled=false

url.item.info=http://services.runescape.com/m=itemdb_rs/api/catalogue/detail.json?item=
url.item.price=http://services.runescape.com/m=itemdb_rs/api/graph/