app:
  version: '@project.version@'
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: runescape
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %5p %X{process_id} --- [%t] %-40.40logger{39} : %m%n%wEx"