app:
  version: '@project.version@'
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: runescape